import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class AuthErrorService {

  constructor() { }

  getErrorMessage(errorCode: string): string {
    const code = errorCode.replace('auth/', '');
    return this.authErrors[code] || "Something went wrong...";
  }

  private authErrors: { [key: string]: string } = {
    "admin-restricted-operation": "This operation is restricted to administrators only.",
    "argument-error": "",
    "app-not-authorized": "This app is not authorized to use Firebase Authentication with the provided API key.",
    "app-not-installed": "The requested mobile application is not installed on this device.",
    "captcha-check-failed": "The reCAPTCHA response token provided is invalid, expired, or already used.",
    "code-expired": "The SMS code has expired. Please re-send the verification code.",
    "cordova-not-ready": "Cordova framework is not ready.",
    "cors-unsupported": "This browser is not supported.",
    "credential-already-in-use": "This credential is already associated with a different user account.",
    "custom-token-mismatch": "The custom token corresponds to a different audience.",
    "requires-recent-login": "This operation requires recent authentication. Log in again before retrying.",
    "dynamic-link-not-activated": "Please activate Dynamic Links in the Firebase Console.",
    "email-change-needs-verification": "Multi-factor users must always have a verified email.",
    "email-already-in-use": "The email address is already in use by another account.",
    "expired-action-code": "The action code has expired.",
    "cancelled-popup-request": "This operation has been cancelled due to another conflicting popup.",
    "internal-error": "An internal error has occurred.",
    "invalid-app-credential": "The phone verification request contains an invalid application verifier.",
    "invalid-app-id": "The mobile app identifier is not registered for the current project.",
    "invalid-user-token": "This user's credential isn't valid for this project.",
    "invalid-auth-event": "An internal error has occurred.",
    "invalid-verification-code": "The SMS verification code is invalid. Please resend the verification code.",
    "invalid-continue-uri": "The continue URL provided is invalid.",
    "invalid-cordova-configuration": "Install the required Cordova plugins for OAuth sign-in.",
    "invalid-custom-token": "The custom token format is incorrect.",
    "invalid-dynamic-link-domain": "The provided dynamic link domain is not configured for the current project.",
    "invalid-email": "The email address is badly formatted.",
    "invalid-api-key": "Your API key is invalid.",
    "invalid-cert-hash": "The SHA-1 certificate hash provided is invalid.",
    "invalid-credential": "Invalid username or password",
    "invalid-message-payload": "The email template contains invalid characters.",
    "invalid-multi-factor-session": "The request does not contain a valid proof of first factor sign-in.",
    "invalid-oauth-provider": "EmailAuthProvider is not supported for this operation.",
    "invalid-oauth-client-id": "The OAuth client ID is invalid or does not match the specified API key.",
    "unauthorized-domain": "This domain is not authorized for OAuth operations.",
    "invalid-action-code": "The action code is invalid. It may be malformed, expired, or already used.",
    "wrong-password": "The password is invalid or the user does not have a password.",
    "invalid-persistence-type": "The specified persistence type is invalid.",
    "invalid-phone-number": "The phone number format is incorrect. Use E.164 format.",
    "invalid-provider-id": "The specified provider ID is invalid.",
    "invalid-recipient-email": "The recipient email address is invalid.",
    "invalid-sender": "The email template contains an invalid sender email or name.",
    "invalid-verification-id": "The verification ID used to create the phone auth credential is invalid.",
    "invalid-tenant-id": "The Auth instance's tenant ID is invalid.",
    "multi-factor-info-not-found": "No matching second factor found for the provided identifier.",
    "multi-factor-auth-required": "Proof of a second factor is required to complete sign-in.",
    "missing-android-pkg-name": "An Android Package Name must be provided.",
    "auth-domain-config-required": "Include authDomain when calling firebase.initializeApp().",
    "missing-app-credential": "The phone verification request is missing an application verifier.",
    "missing-verification-code": "The SMS verification code is missing.",
    "missing-continue-uri": "A continue URL must be provided.",
    "missing-iframe-start": "An internal error has occurred.",
    "missing-ios-bundle-id": "An iOS Bundle ID must be provided.",
    "missing-multi-factor-info": "No second factor identifier is provided.",
    "missing-multi-factor-session": "Proof of first factor sign-in is missing.",
    "missing-or-invalid-nonce": "The request does not contain a valid nonce.",
    "missing-phone-number": "Provide a phone number for verification codes.",
    "missing-verification-id": "The phone auth credential was created with an empty verification ID.",
    "app-deleted": "This instance of FirebaseApp has been deleted.",
    "account-exists-with-different-credential": "An account exists with the same email but different credentials.",
    "network-request-failed": "A network error has occurred.",
    "no-auth-event": "An internal error has occurred.",
    "no-such-provider": "User not linked to an account with the given provider.",
    "null-user": "A null user object was provided.",
    "operation-not-allowed": "The given sign-in provider is disabled.",
    "operation-not-supported-in-this-environment": "This operation is not supported in this environment.",
    "popup-blocked": "The popup may have been blocked by the browser.",
    "popup-closed-by-user": "The popup was closed by the user before finalizing.",
    "provider-already-linked": "User can only be linked to one identity for the given provider.",
    "quota-exceeded": "The quota for this operation has been exceeded.",
    "redirect-cancelled-by-user": "The redirect operation was cancelled by the user.",
    "redirect-operation-pending": "A redirect sign-in operation is already pending.",
    "rejected-credential": "The request contains malformed or mismatching credentials.",
    "second-factor-already-in-use": "The second factor is already enrolled on this account.",
    "maximum-second-factor-count-exceeded": "The maximum number of second factors has been exceeded.",
    "tenant-id-mismatch": "The provided tenant ID does not match the Auth instance's tenant ID.",
    "timeout": "The operation has timed out.",
    "user-token-expired": "The user's credential is no longer valid. Please sign in again.",
    "too-many-requests": "All requests from this device have been blocked due to unusual activity.",
    "unauthorized-continue-uri": "The domain of the continue URL is not whitelisted.",
    "unsupported-first-factor": "A supported first factor is required for multi-factor accounts.",
    "unsupported-persistence-type": "The specified persistence type is not supported.",
    "unsupported-tenant-operation": "This operation is not supported in a multi-tenant context.",
    "unverified-email": "The operation requires a verified email.",
    "user-cancelled": "The user did not grant the requested permissions.",
    "user-not-found": "No user record found for this identifier.",
    "user-disabled": "The user account has been disabled.",
    "user-mismatch": "The supplied credentials do not match the previously signed in user.",
    "user-signed-out": "",
    "weak-password": "The password must be 6 characters long or more.",
    "web-storage-unsupported": "This browser is not supported or 3rd party cookies may be disabled."
  };
}
